hairsalon_app/users/routes.py
from decimal import Decimal
from flask import Blueprint, current_app, flash, url_for, redirect, render_template,request
from flask_login import LoginManager, current_user, login_required, login_user, logout_user
from hairsalon_app.qdb.database import db
from flask_bcrypt import Bcrypt
import secrets
import os
from PIL import Image
from markupsafe import escape
from hairsalon_app.users.Member import Member
from hairsalon_app.users.forms import LoginForm, NewUserForm, NewUserFormAdmin, UpdateProfileAdminForm, UpdateProfileForm, UpdateImageForm

#Create an instance of Database
login_manager = LoginManager()

#Create a blueprint
users_bp = Blueprint("users_bp",__name__,template_folder='templates', static_folder='static', static_url_path='/users/static')

#Registration of a user
@users_bp.route('/register/', methods=['GET', 'POST'])
def register():
    """ Method for the registration of a user """
    form = NewUserForm()
    if form.password.data != form.confirm_password.data: 
        flash('Passwords do not match!', 'error')
    elif form.validate_on_submit():
        # Check if this user already exists
        if form.user_image.data:
            file_name = save_file(form_file=form.user_image.data)
        else:
            file_name = 'default.png'
        member_exists = db.get_members_cond(f"username = '{form.username.data}'")
        if not member_exists:
            b = Bcrypt()
            hashed_pass = b.generate_password_hash(form.password.data).decode('utf-8')
            if form.pay_rate.data == Decimal('0.00') and form.specialty.data == '':
                db.add_new_member(  user_type='client',
                    username=form.username.data, 
                    full_name=form.full_name.data,
                    email=form.email.data,
                    user_image=file_name,
                    password=hashed_pass, 
                    phone=form.phone_number.data,
                    address=form.address.data,
                    age=form.age.data)
            else:
                db.add_new_member( user_type='professional',
                                username=form.username.data, 
                                full_name=form.full_name.data,
                                email=form.email.data,
                                user_image=file_name,
                                password=hashed_pass, 
                                phone=form.phone_number.data,
                                address=form.address.data,
                                age=form.age.data, 
                                speciality=form.specialty.data,
                                payrate=form.pay_rate.data)
            flash('Successful registration! Please Login to continue...', 'success')
            return redirect(url_for('users_bp.login'))
        else:
            flash('This account already exists.', 'error')
            return redirect(url_for('users_bp.login'))
    return render_template('register.html', form=form)  #redirect to login page???

#Login of a user
@users_bp.route('/login/', methods=['GET', 'POST'])
def login():
    """ Method for the login of a user """
    form = LoginForm()
    if form.validate_on_submit():
        username=form.username.data
        user_exists = db.get_members_cond(condition=f"username = '{username}'")
        if user_exists:
            user_exists = user_exists[0]
            if user_exists.is_active[0] == 1:
                flash('Your account has been deactivated by the admin. Please contact us.', 'error')
                return redirect(url_for('main_bp.home'))
            b = Bcrypt()
            password_hashed = user_exists.password
            if b.check_password_hash(password_hashed, form.password.data):
                login_user(user_exists)
                if user_exists.status == 1:
                    flash('Your account has been flagged. You are actions are being monitored.', 'info')
                flash(f'Success: Logged in as {form.username.data}', 'success')
                return redirect(url_for('main_bp.home'))
        flash ('Invalid password or username. Retry', 'error')        
    return render_template('login.html', form=form)

#Route to general profile of a user
@users_bp.route('/profile/<string:username>/')
@login_required
def profile(username):
    """Returns to the profile using the given username. """
    if username != current_user.username:
        flash("This is not your profile", 'error')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    user = db.get_members_cond(f"username = '{username}'")
    if not user:
        flash('User does not exist', 'error')
        return redirect(url_for('main_bp.home'))
    user = user[0]
    return render_template('Profile.html', users=user)

#Route to edit profile of a user
@users_bp.route('/profile/edit/<string:username>/', methods=['GET', 'POST'])
@login_required 
def edit_profile(username):
    """Edits the profile and returns to his profile if the update was successeful """
    if current_user.username != username:
        flash("This is not your profile", 'error')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    form1 = UpdateImageForm()
    form = UpdateProfileForm()
    user = db.get_members_cond(f"username = '{username}'")
    if not user:
        flash('User does not exist', 'error')
        return redirect(url_for('main_bp.home'))
    user = user[0]
    if request.method == 'POST':
        full_name = form.full_name.data if form.full_name.data else user.full_name
        email = form.email.data if form.email.data else user.email
        phone_number = form.phone_number.data if form.phone_number.data else user.phone_number
        address = form.address.data if form.address.data else user.address
        # Handle user_image file upload
        if form1.user_image.data:
            file_name = save_file(form1.user_image.data)  
        else:
            file_name = user.user_image
        if form.new_password.data and form.new_password.data :
            b = Bcrypt()
            if b.check_password_hash(user.password, form.old_password.data):
                b = Bcrypt()
                hashed_new_pass = b.generate_password_hash(form.new_password.data).decode('utf-8')
                password = hashed_new_pass
            else:
                flash('You inputed the wrong password for you account.Please input the information correctly!','error')
                password = user.password
        else:
            password = user.password
        db.update_profile(username=user.username,
                          new_password= password, 
                          full_name=full_name, email=email,  
                          phone_number=phone_number, 
                          address=address, 
                          user_image=file_name)
        flash('Successful update!','success')
        return redirect(url_for('users_bp.profile', username=user.username))
    return render_template('update_profile.html', form=form, form1=form1, users=user)

#Route to edit profile of a user by the admin
@users_bp.route('/profile/admin_edit/<string:username>/', methods=['GET', 'POST'])
@login_required 
def edit_profile_admin(username):
    """Method where admin user can edit the profile of a user"""
    if current_user.user_type != 'admin_super' and \
            current_user.user_type != 'admin_user':
        flash('You must be admin appoint or super to access this view', 'info')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    form = UpdateProfileAdminForm()
    user = db.get_members_cond(f"username = '{username}'")
    if form.validate_on_submit():
        if form.user_image.data:
            file_name = save_file(form.user_image.data)  
        else:
            file_name = user[0].user_image
        if form.new_password.data:
            b = Bcrypt()
            hashed_new_pass = b.generate_password_hash(form.new_password.data).decode('utf-8')
            password = hashed_new_pass
        else:
            password = user[0].password
        db.update_profile_admin(user_id=user[0].user_id, 
                                user_type=form.user_type.data, 
                                username=form.username.data, 
                                full_name=form.full_name.data,
                                new_password=password, 
                                email=form.email.data, 
                                phone_number=form.phone_number.data,
                                address=form.address.data, 
                                age=form.age.data, 
                                speciality=form.speciality.data,
                                pay_rate=form.pay_rate.data, 
                                user_image=file_name)
        flash('Successful update!', 'success')
        return redirect(url_for('users_bp.admin_pannel'))
    return render_template('edit_profile_admin.html', user=user[0], form=form)

#Route to the admin pannel 
@users_bp.route('/admin-pannel/', methods=['GET', 'POST'])
@login_required 
def admin_pannel():
    """Returns to the admin pannel """
    if 'admin' not in current_user.user_type:
        flash('You must be admin appoint or super to access this view', 'info')
        return redirect(url_for('main_bp.home'))
    form = NewUserFormAdmin()
    logs = db.get_all_logs()
    client_list = db.get_members_cond(condition="(user_type='client')")
    employee_list = db.get_members_cond(condition="user_type NOT IN ('admin_super', 'client')")
    app_list = db.appointments_cond()

    if form.validate_on_submit():
        file_name = save_file(form_file=form.user_image.data) if form.user_image.data else 'default.png'
        member_exists = db.get_members_cond(f"username = '{form.username.data}'")
        if not member_exists:
            b = Bcrypt()
            hashed_pass = b.generate_password_hash(form.password.data).decode('utf-8')

hairsalon_app/users/templates/Profile.html
{% extends 'home.html' %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/profile.css')}}">
<script src="{{url_for('users_bp.static', filename='js/profile.js')}}"></script>
{% endblock content_css %}
{% block content_side_pannel %}
<div id="image_div">
    <h2> {{users.full_name}}</h2>
    <h5> @{{users.username}}</h5>
    <img src="{{ url_for('static', filename='images/user-pics/' + users.user_image) }}" alt="Profile picture of user">
    {% if users.user_type == 'professional' %}
    <h5> Speciality: {{ users.speciality}} </h5>
    {% endif %}
    <p> User Type: {{ users.user_type}} </p><br>
    <p> Address :{{users.address}} </p><br>
    <p>{{users.email}} </p><br>
    <p> Age: {{users.age}} </p><br>
    <fieldset id="text">
        All user information is protected by the privacy politics we instored in place.
    </fieldset>
</div>
{% endblock %}
{% block content_main_pannel %}

<div class="button-container">
    <div class="hidden-element" id="hoverElement">
        <h2> You want to update your profile info? </h2><br>
        <h4> CLICK BELOW ↓ </h4>
    </div>
</div>
<div class = "container">
    <div id="update_button">
        <button type="button" id="hoverButton"> <a href="{{url_for('users_bp.edit_profile', username=users.username)}}">Update profile</a> </button>
    </div>
  </div>
{% endblock %}

hairsalon_app/users/templates/admin_panel.html
{% extends 'home.html'%}
{% from "macro.html" import form_field_error with context %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/admin_panel.css')}}">
<script src="{{url_for('users_bp.static', filename='js/validation.js')}}"></script>
<script src="{{url_for('users_bp.static', filename='js/admin_panel.js')}}"></script>
{% endblock content_css %}
{% block content_side_pannel %}
{% if current_user.user_type == 'admin_super' or current_user.user_type == 'admin_user' %}
<h4>Create User</h4>
<div class="register-div" id="create-user">
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <fieldset>
            <label for="user-create">Create a user of type...</label>
            {{ form.user_type(class='form-control', id='user-create') }}    
            {{form.username (class='form-field', placeholder="Username", id="username")}}
            {{form_field_error(form.username.errors)}}
            {{form.full_name(class='form-field', placeholder="full_name", id="full_name")}}
            {{form_field_error(form.full_name.errors)}}
            {{form.email (class='form-field', placeholder="Email", id="email")}}
            {{form_field_error(form.email.errors)}}
            {{form.password(class='form-field', placeholder='Password', id="password")}}
            {{form_field_error(form.password.errors)}}
            {{form.confirm_password(class='form-field', placeholder='Confirm_password', id="confirm-password")}}
            {{form_field_error(form.confirm_password.errors)}}
            <section>
                {{ form.user_image(class='form-field') }}
                {{form_field_error(form.user_image.errors)}}
            </section>
            {{form.phone_number(class='form-field', placeholder='Phone Number', id="phone_number")}}
            {{form_field_error(form.phone_number.errors)}}
            {{form.address(class='form-field', placeholder='Street Number, Province, Country', id="address")}}
            {{form_field_error(form.address.errors)}}
            {{form.age(class='form-field', placeholder='Age', id="age")}}
            {{form_field_error(form.age.errors)}}
            <section id="non-client-fields">
                {{form.pay_rate(class='form-field', placeholder='Pay Rate')}}
                {{form_field_error(form.pay_rate.errors)}}
                {{form.specialty(class='form-field', placeholder='Specialty')}}
                {{form_field_error(form.specialty.errors)}}
            </section>
        </fieldset>
        {{form.submit(class='create-button')}}
    </form>
</div>
{% endif %}
{% endblock content_side_pannel %}
{% block content_main_pannel %}
<h2>Admin Pannel {{current_user.user_type}}</h2>
<div class="admin_pannel">
    <nav>
        <ul id="adminnav-menu">
            {% if current_user.user_type == 'admin_super' or current_user.user_type == 'admin_user' %}
            <li>Clients</li>
            <li>Employees</li>
            {% endif %}
            {% if current_user.user_type == 'admin_super' or current_user.user_type == 'admin_appoint' %}
            <li>Appointments</li>
            {% endif %}
            <li>Logs</li>
        </ul>
    </nav> 
    <div id="Client-list" class="content">
        <h3>Client List</h3>
        <table class="admin-table">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Full Name</th>
                <th>Active</th>
                <th>Picture</th>
                <th>Flag</th>
                <th>Edit/Delete</th>
            </tr>
            {% for client in clients %}
            <tr>
                <td>{{ client.id }}</td> 
                <td>{{ client.username }}</td>
                <td>{{ client.full_name }}</td>
                {% if client.is_active[0] == 0 %}
                <td class="access">
                    <button>
                        <a href="{{url_for('users_bp.toggle_active_user', username=client.username)}}">Activated</a>
                    </button>
                </td>
                {% else %}
                <td class="access deactivated">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_active_user', username=client.username)}}">Deactivated</a>
                    </button>
                </td>
                {% endif %}
                <td><img src="{{ url_for('static', filename='images/user-pics/' + client.user_image) }}" alt="Profile picture of user"></td>
                {% if client.status == 0 %}
                <td class="flag">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_flag', username=client.username)}}">Unflagged</a>
                    </button>
                </td>
                {% else %}
                <td class="flag flagged"> 
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_flag', username=client.username)}}">Flagged</a>
                    </button>
                </td>
                {% endif %}
                <td>
                    <button>
                        <a href="{{url_for('users_bp.edit_profile_admin', username=client.username)}}">Details</a>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div id="Employees-list" class="content">
        <h3>Employee List</h3>
        <table class="admin-table">
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Full Name</th>
                <th>Active</th>
                <th>Picture</th>
                <th>Flag</th>
                <th>Edit/Delete</th>
            </tr>
            {% for employee in employees %}
            <tr>
                <td>{{employee.user_id}}</td>
                <td>{{employee.username}}</td>
                <td>{{employee.full_name}}</td>    
                {% if employee.is_active[0] == 0 %}
                <td class="access">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_active_user', username=employee.username)}}">Activated</a>
                    </button>
                </td>
                {% else %}
                <td class="access deactivated">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_active_user', username=employee.username)}}">Deactivated</a>
                    </button>
                </td>
                {% endif %}
                <td><img src="{{ url_for('static', filename='images/user-pics/' + employee.user_image) }}" alt="Profile picture of user"></td>
                {% if employee.status == 0 %}
                <td class="flag">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_flag', username=employee.username)}}">Unflagged</a>
                    </button>
                </td>
                {% else %}
                <td class="flag flagged">
                    <button>
                        <a class="custom-link" href="{{url_for('users_bp.toggle_flag', username=employee.username)}}">Flagged</a>
                    </button>
                </td>
                {% endif %}
                <td>
                    <button>
                        <a href="{{url_for('users_bp.edit_profile_admin', username=employee.username)}}">Details</a>
                    </button>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    <div id="Appointments-list" class="content">
        <h3>Appointment List With Reports</h3>
        <button class="specific-button-admin">
            <a href="{{url_for('appointment_bp.create_appointment')}}">Create New Appointment</a>
        </button>
        <table class="admin-table">
            <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Date</th>
                <th>Client</th>
                <th>Employee</th>
                <th>View Details / Modify</th>
            </tr>
            {% for app in appointments %}
            <tr>
                <td>{{app.appointment_id}}</td>
                <td>{{app.status}}</td>
                <td>{{app.date_appointment}}</td>
                <td>{{app.client_name}}</td>
                <td>{{app.professional_name}}</td>
                <td><a class="app-link" href="{{url_for('appointment_bp.specific_appointment', appointment_id=app.appointment_id)}}">Details</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>   
    <div id="logs" class="content">
        <h3>All logs</h3>
        <button class="specific-button-admin">
            <a href="{{url_for('users_bp.clear_logs')}}">Clear Logs</a>
        </button>
        <table class="admin-table">
            <tr>
                <th>User ID</th>
                <th>Action</th>
                <th>Table Name</th>
                <th>Date and Time</th>
            </tr>
            {% for log in logs %}
            <tr>
                <td>{{log[2]}}</td>
                <td>{{log[0]}}</td>
                <td>{{log[1]}}</td>
                <td>{{log[3]}}</td>
            </tr>
            {% endfor %}
        </table>
    </div> 
</div>
{% endblock content_main_pannel %}

hairsalon_app/users/templates/edit_profile_admin.html
{% extends 'home.html' %}
{% from "macro.html" import form_field_error with context %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/update.css')}}">
<script src="{{url_for('users_bp.static', filename='js/validation.js')}}"></script>
{% endblock content_css %}
{% block content_side_pannel %}
<div>
    <div id="image_div">
        <h2> {{user.full_name}}</h2>
        <h5> @{{user.username}}</h5>
        <img src="{{ url_for('static', filename='images/user-pics/' + user.user_image) }}" alt="Profile picture of user">
        <p id="text">
            Upload any image in the following format: png, jpg, jpeg, webp.
        </p>
    </div>
</div>
{% endblock %}
{% block content_main_pannel %}
<div  id="info_div">
    <h2>Edit Admin Profile</h2>
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <fieldset id="info">
            <label for="user_type">User's Type</label>
            {{ form.user_type(class='form-field', id='user_type', value=user.user_type) }}
            {{form_field_error(form.user_type.errors)}}
            <label for="username">Username</label>
            {{ form.username(class='form-field', id='username', value=user.username) }}
            {{form_field_error(form.username.errors)}}
            <label for="full_name">Full Name</label>
            {{ form.full_name(class='form-field', id='full_name', value=user.full_name) }}
            {{form_field_error(form.full_name.errors)}}
            <label for="new_password">New Password</label>
            {{ form.new_password(class='form-field', id='new_password', value=user.password) }}
            {{form_field_error(form.new_password.errors)}}
            <label for="email">Email</label>
            {{ form.email(class='form-field', id='email', value=user.email) }}
            {{form_field_error(form.email.errors)}}
            <label for="phone_number">Phone Number</label>
            {{ form.phone_number(class='form-field', id='phone_number', value=user.phone_number) }}
            {{form_field_error(form.phone_number.errors)}}
            <label for="address">Address</label>
            {{ form.address(class='form-field', id='address', value=user.address) }}
            {{form_field_error(form.address.errors)}}
            <label for="age">Age</label>
            {{ form.age(class='form-field', id='age', value=user.age) }}
            {{form_field_error(form.age.errors)}}
            {% if user.user_type != 'client' %}
                <label for="speciality">Specialty</label>
                {{ form.speciality(class='form-field', id='speciality', value=user.speciality) }}
                {{form_field_error(form.speciality.errors)}}
                <label for="pay_rate">Pay Rate</label>
                {{ form.pay_rate(class='form-field', id='pay_rate', value=user.pay_rate) }}        
                {{ form_field_error(form.pay_rate.errors)}}
            {% endif %}
            <label for="user_image">Profile Picture</label>
            {{form.user_image(class='form-field', id='user_image', value=user.user_image)}}
        </fieldset> 
        <div class ="upd_buttons">
        {{form.submit(class='button')}}
        </div>
    </form>
    <div class="upd_buttons">
        <button id="delete-button">
            <a href="{{url_for('users_bp.delete_user', username=user.username)}}">Delete User</a>
        </button>
    </div>
</div>
{% endblock content_main_pannel %}

hairsalon_app/users/templates/login.html
{% extends 'base.html' %}
{% from "macro.html" import form_field_error with context %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/login.css')}}">
<script src="{{url_for('users_bp.static', filename='js/loginValidation.js')}}"></script>
{% endblock content_css %}
{% block content_side_pannel %}
<p>Welcome Back</p>
{% endblock content_side_pannel %}
{% block content_main_pannel %}
<div id="login-div">
    <form method="POST" action="">
        <h2>Login</h2>
        {{form.hidden_tag()}}
        <fieldset>
            {{form.username(class='form-field', placeholder='Username', id="username")}}
            {{form_field_error(form.username.errors)}}
            {{form.password(class='form-field', placeholder='Password', id="password")}}
            {{form_field_error(form.password.errors)}}
        </fieldset>
        {{form.submit(class='button')}}
    </form>
    <div class="register-link">
        <a href="{{url_for('users_bp.register')}}">Don't have an account?</a>
    </div>
</div>

{% endblock content_main_pannel %}

hairsalon_app/users/templates/register.html
{% extends 'base.html' %}
{% from "macro.html" import form_field_error with context %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/registration.css')}}">
<script src="{{url_for('users_bp.static', filename='js/registration.js')}}"></script>
<script src="{{url_for('users_bp.static', filename='js/validation.js')}}"></script>
{% endblock content_css%}
{% block content_side_pannel %}
<h4> Welcome </h4>
{% endblock content_side_pannel %}
{% block content_main_pannel %}
<h2>Register With Us</h2>
<input type="checkbox" id="toggle" class="toggleCheckbox" value="pro"/>
<!-- pro=on if checked -->
    <label for='toggle' class='toggleContainer'>
        <div>Client</div> 
        <div>Professional</div>
    </label>
<div id="register-div">
    <form action="" method="POST" enctype="multipart/form-data" novalidate>
        {{ form.hidden_tag() }}
        <fieldset>
            {{form.username (class='form-field', placeholder="Username", id="username")}}
            {{form_field_error(form.username.errors)}}
            {{form.full_name(class='form-field', placeholder="full_name", id="full_name")}}
            {{form_field_error(form.full_name.errors)}}
            {{form.email (class='form-field', placeholder="Email", id="email")}}
            {{form_field_error(form.email.errors)}}
            {{form.password(class='form-field', placeholder='Password', id="password")}}
            {{form_field_error(form.password.errors)}}
            {{form.confirm_password(class='form-field', placeholder='Confirm_password', id="confirm-password")}}
            {{form_field_error(form.confirm_password.errors)}}
            <section>
                {{ form.user_image(class='form-field') }}
                {{form_field_error(form.user_image.errors)}}
            </section>
            {{form.phone_number(class='form-field', placeholder='Phone Number', id="phone_number")}}
            {{form_field_error(form.phone_number.errors)}}
            {{form.address(class='form-field', placeholder='Street Number, Province, Country', id="address")}}
            {{form_field_error(form.address.errors)}}
            {{form.age(class='form-field', placeholder='Age', id="age")}}
            {{form_field_error(form.age.errors)}}
            <section id="pro-fields">
                {{form.pay_rate(class='form-field', placeholder='Pay Rate', id="pay_rate")}}
                {{form_field_error(form.pay_rate.errors)}}
                {{form.specialty(class='form-field', placeholder='Specialty', id="specialty")}}
                {{form_field_error(form.specialty.errors)}}
            </section>
        </fieldset>
        {{form.submit(class='button')}}
    </form>
</div>

{% endblock content_main_pannel %}

hairsalon_app/users/templates/update_profile.html
{% extends 'home.html' %}
{% from "macro.html" import form_field_error with context %}
{% block content_css %}
<link rel="stylesheet" href="{{url_for('users_bp.static', filename='css/update.css')}}">
{% endblock content_css %}
{% block content_side_pannel %}
    <div id="image_div">
        <h2> {{users.full_name}}</h2>
        <h5> @{{users.username}}</h5>
        <img src="{{ url_for('static', filename='images/user-pics/' + users.user_image) }}" alt="Profile picture of user">
        <form action="" method="POST" enctype="multipart/form-data" novalidate>
            {{form1.hidden_tag() }}
            <fieldset>
                {{form1.user_image(class='form-field', placeholder='Upload New Photo') }}
                {{form_field_error(form1.user_image.errors)}}
                {{form1.submit(class='button')}}
            </fieldset>
        </form>
        <fieldset class="text">
            Upload any image in the following format: png, jpg, jpeg, webp.
        </fieldset>
    </div>

{% endblock %}
{% block content_main_pannel %}
<div id="info_div">
<h2>Edit profile</h2>
    <form action="" method="POST" enctype="multipart/form-data" novalidate >
        {{ form.hidden_tag() }}
        <fieldset id="info">
            <div class = "div_space">
                <label for="full_name">Full Name</label>
                {{form.full_name(class='form-field', placeholder="full_name", value=users.full_name)}}
                {{form_field_error(form.full_name.errors)}}
            </div>
            <div class = "div_space">
                <label for="email">Email</label>
                {{form.email (class='form-field', placeholder="Email", value=users.email)}} 
                {{form_field_error(form.email.errors)}}
            </div>
            <div class = "div_space">
                <label for="old_password">Old Password</label>
                {{form.old_password(class='form-field', placeholder='Old Password')}}
                {{form_field_error(form.old_password.errors)}}
            </div>
            <div class = "div_space">
                <label for="new_password">New Password</label>
                {{form.new_password(class='form-field', placeholder='New password')}} 
                {{form_field_error(form.new_password.errors)}}
            </div>
            <div class = "div_space">
                <label for="phone_number">Phone Number</label>
                {{form.phone_number(class='form-field', placeholder='Phone Number',  value=users.phone_number)}}
                {{form_field_error(form.phone_number.errors)}}
            </div>
            <div class = "div_space">
                <label for="address">Address</label>
                {{form.address(class='form-field', placeholder='Street Number, Province, Country', value=users.address )}}<br>
                {{form_field_error(form.address.errors)}}
            </div>
            <div id="submit_button">
                {{form.submit(class='button')}}
            </div> 
            <div class="text">
                Leave the field blank if you don't want to udpate the specific field.
            </div>
        </fieldset>
    </form>
</div>
{% endblock content_main_pannel %}