hairsalon_app/main_view/routes.py
from flask import Blueprint, render_template
from hairsalon_app.qdb.database import db


main_bp = Blueprint('main_bp', __name__, template_folder='templates',static_folder='static', static_url_path='/main_view/static')

@main_bp.route('/about')
def about():
    """Return the about page."""
    return render_template('about.html')

@main_bp.route('/home/')
@main_bp.route('/')
def home():
    """Return the home page."""
    list_services = db.services_cond()
    return render_template('home.html',services=list_services)

@main_bp.route('/api/')
def api_docs():
    """Return the api docs page."""
    return render_template('api_docs.html')

hairsalon_app/users/routes.py
from decimal import Decimal
from flask import Blueprint, current_app, flash, url_for, redirect, render_template,request
from flask_login import LoginManager, current_user, login_required, login_user, logout_user
from hairsalon_app.qdb.database import db
from flask_bcrypt import Bcrypt
import secrets
import os
from PIL import Image
from markupsafe import escape
from hairsalon_app.users.Member import Member
from hairsalon_app.users.forms import LoginForm, NewUserForm, NewUserFormAdmin, UpdateProfileAdminForm, UpdateProfileForm, UpdateImageForm

#Create an instance of Database
login_manager = LoginManager()

#Create a blueprint
users_bp = Blueprint("users_bp",__name__,template_folder='templates', static_folder='static', static_url_path='/users/static')

#Registration of a user
@users_bp.route('/register/', methods=['GET', 'POST'])
def register():
    """ Method for the registration of a user """
    form = NewUserForm()
    if form.password.data != form.confirm_password.data: 
        flash('Passwords do not match!', 'error')
    elif form.validate_on_submit():
        # Check if this user already exists
        if form.user_image.data:
            file_name = save_file(form_file=form.user_image.data)
        else:
            file_name = 'default.png'
        member_exists = db.get_members_cond(f"username = '{form.username.data}'")
        if not member_exists:
            b = Bcrypt()
            hashed_pass = b.generate_password_hash(form.password.data).decode('utf-8')
            if form.pay_rate.data == Decimal('0.00') and form.specialty.data == '':
                db.add_new_member(  user_type='client',
                    username=form.username.data, 
                    full_name=form.full_name.data,
                    email=form.email.data,
                    user_image=file_name,
                    password=hashed_pass, 
                    phone=form.phone_number.data,
                    address=form.address.data,
                    age=form.age.data)
            else:
                db.add_new_member( user_type='professional',
                                username=form.username.data, 
                                full_name=form.full_name.data,
                                email=form.email.data,
                                user_image=file_name,
                                password=hashed_pass, 
                                phone=form.phone_number.data,
                                address=form.address.data,
                                age=form.age.data, 
                                speciality=form.specialty.data,
                                payrate=form.pay_rate.data)
            flash('Successful registration! Please Login to continue...', 'success')
            return redirect(url_for('users_bp.login'))
        else:
            flash('This account already exists.', 'error')
            return redirect(url_for('users_bp.login'))
    return render_template('register.html', form=form)  #redirect to login page???

#Login of a user
@users_bp.route('/login/', methods=['GET', 'POST'])
def login():
    """ Method for the login of a user """
    form = LoginForm()
    if form.validate_on_submit():
        username=form.username.data
        user_exists = db.get_members_cond(condition=f"username = '{username}'")
        if user_exists:
            user_exists = user_exists[0]
            if user_exists.is_active[0] == 1:
                flash('Your account has been deactivated by the admin. Please contact us.', 'error')
                return redirect(url_for('main_bp.home'))
            b = Bcrypt()
            password_hashed = user_exists.password
            if b.check_password_hash(password_hashed, form.password.data):
                login_user(user_exists)
                if user_exists.status == 1:
                    flash('Your account has been flagged. You are actions are being monitored.', 'info')
                flash(f'Success: Logged in as {form.username.data}', 'success')
                return redirect(url_for('main_bp.home'))
        flash ('Invalid password or username. Retry', 'error')        
    return render_template('login.html', form=form)

#Route to general profile of a user
@users_bp.route('/profile/<string:username>/')
@login_required
def profile(username):
    """Returns to the profile using the given username. """
    if username != current_user.username:
        flash("This is not your profile", 'error')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    user = db.get_members_cond(f"username = '{username}'")
    if not user:
        flash('User does not exist', 'error')
        return redirect(url_for('main_bp.home'))
    user = user[0]
    return render_template('Profile.html', users=user)

#Route to edit profile of a user
@users_bp.route('/profile/edit/<string:username>/', methods=['GET', 'POST'])
@login_required 
def edit_profile(username):
    """Edits the profile and returns to his profile if the update was successeful """
    if current_user.username != username:
        flash("This is not your profile", 'error')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    form1 = UpdateImageForm()
    form = UpdateProfileForm()
    user = db.get_members_cond(f"username = '{username}'")
    if not user:
        flash('User does not exist', 'error')
        return redirect(url_for('main_bp.home'))
    user = user[0]
    if request.method == 'POST':
        full_name = form.full_name.data if form.full_name.data else user.full_name
        email = form.email.data if form.email.data else user.email
        phone_number = form.phone_number.data if form.phone_number.data else user.phone_number
        address = form.address.data if form.address.data else user.address
        # Handle user_image file upload
        if form1.user_image.data:
            file_name = save_file(form1.user_image.data)  
        else:
            file_name = user.user_image
        if form.new_password.data and form.new_password.data :
            b = Bcrypt()
            if b.check_password_hash(user.password, form.old_password.data):
                b = Bcrypt()
                hashed_new_pass = b.generate_password_hash(form.new_password.data).decode('utf-8')
                password = hashed_new_pass
            else:
                flash('You inputed the wrong password for you account.Please input the information correctly!','error')
                password = user.password
        else:
            password = user.password
        db.update_profile(username=user.username,
                          new_password= password, 
                          full_name=full_name, email=email,  
                          phone_number=phone_number, 
                          address=address, 
                          user_image=file_name)
        flash('Successful update!','success')
        return redirect(url_for('users_bp.profile', username=user.username))
    return render_template('update_profile.html', form=form, form1=form1, users=user)

#Route to edit profile of a user by the admin
@users_bp.route('/profile/admin_edit/<string:username>/', methods=['GET', 'POST'])
@login_required 
def edit_profile_admin(username):
    """Method where admin user can edit the profile of a user"""
    if current_user.user_type != 'admin_super' and \
            current_user.user_type != 'admin_user':
        flash('You must be admin appoint or super to access this view', 'info')
        return redirect(url_for('main_bp.home'))
    username=escape(username)
    form = UpdateProfileAdminForm()
    user = db.get_members_cond(f"username = '{username}'")
    if form.validate_on_submit():
        if form.user_image.data:
            file_name = save_file(form.user_image.data)  
        else:
            file_name = user[0].user_image
        if form.new_password.data:
            b = Bcrypt()
            hashed_new_pass = b.generate_password_hash(form.new_password.data).decode('utf-8')
            password = hashed_new_pass
        else:
            password = user[0].password
        db.update_profile_admin(user_id=user[0].user_id, 
                                user_type=form.user_type.data, 
                                username=form.username.data, 
                                full_name=form.full_name.data,
                                new_password=password, 
                                email=form.email.data, 
                                phone_number=form.phone_number.data,
                                address=form.address.data, 
                                age=form.age.data, 
                                speciality=form.speciality.data,
                                pay_rate=form.pay_rate.data, 
                                user_image=file_name)
        flash('Successful update!', 'success')
        return redirect(url_for('users_bp.admin_pannel'))
    return render_template('edit_profile_admin.html', user=user[0], form=form)

#Route to the admin pannel 
@users_bp.route('/admin-pannel/', methods=['GET', 'POST'])
@login_required 
def admin_pannel():
    """Returns to the admin pannel """
    if 'admin' not in current_user.user_type:
        flash('You must be admin appoint or super to access this view', 'info')
        return redirect(url_for('main_bp.home'))
    form = NewUserFormAdmin()
    logs = db.get_all_logs()
    client_list = db.get_members_cond(condition="(user_type='client')")
    employee_list = db.get_members_cond(condition="user_type NOT IN ('admin_super', 'client')")
    app_list = db.appointments_cond()

    if form.validate_on_submit():
        file_name = save_file(form_file=form.user_image.data) if form.user_image.data else 'default.png'
        member_exists = db.get_members_cond(f"username = '{form.username.data}'")
        if not member_exists:
            b = Bcrypt()
            hashed_pass = b.generate_password_hash(form.password.data).decode('utf-8')

hairsalon_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hair Salon App</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/mobile.css')}}">
    {% block content_css %}{% endblock content_css %}
</head>
<body>
    <nav id="nav-main">
        <div id ="left-nav">
            <ul>
                <li id="saloon-header">
                    <h3>Saloon</h3>
                    <img id="logo" src="{{ url_for('static', filename='images/logo1.png') }}" alt="logo for web">
                </li>            
                <li><a href="{{url_for('main_bp.home')}}">Home</a></li>
                <li><a href="{{url_for('main_bp.about')}}">About Us</a></li>
                <li><a href="{{url_for('main_bp.api_docs')}}">API</a></li>
            </ul>
        </div>
        <section id="flash-errors">
            {% if get_flashed_messages() %}
            <ul>
                 <!-- with categories true meaning we get the category, plus the message. [0] = category, [1] = message itself  -->
                {% for message in get_flashed_messages(with_categories=True) %}
                    {% if 'success' in message[0] %}
                        <li class="success">{{ message[1] }}</li>
                    {% elif 'error' in message[0] %}
                        <li class="error">{{ message[1] }}</li>
                    {% elif 'info' in message[0] %}
                        <li class="info">{{ message[1] }}</li>
                    {% endif %}
                {% endfor %}  
            </ul>
            {% endif %}
        </section>
        <div id="right-nav">
            <nav>
                <ul >
                    {% block content_when_login %}
                    <li> 
                        <a href="{{url_for('users_bp.login')}}">Login</a>
                    </li>
                    <li>
                        <a href="{{ url_for('users_bp.register') }}">Register</a>
                    </li>
                    <li> 
                        <a href="{{url_for('appointment_bp.all_appointments')}}">Appointments</a>
                    </li>
                    {% endblock %}
                </ul>
            </nav>
        </div> 
    </nav>
    <main>
        <div id="side-pannel">
        {% block content_side_pannel %}
             <!-- In the respective templates, override this block to add content for your view.  --> 
        {% endblock content_side_pannel %}         
        </div>
        <div id="main-pannel">
            {% block content_main_pannel %}
            <!-- In the respective templates, override this block to add content for your view. -->
            {% endblock %}
        </div>
    </main>
    <footer>
        <div>
        <p class="semi-transparent-bg">Developers: Amy Nguyen, Iana Fenuic, Darina Hojeij</p>
        <p class="semi-transparent-bg">Winter 2024 - 420 Final Project</p>
        <p class="semi-transparent-bg">Dawson College 420.B0</p>
        </div>
    </footer>
</body>
</html>

hairsalon_app/templates/custom404.html
{% extends 'home.html' %}
{% block content_side_pannel%}
<h4>404</h4>
{% endblock %}
{% block content_main_pannel %}
<p>The Page you were looking for does not exist or cannot be found.</p>
{% endblock %}

hairsalon_app/templates/loggedIn.html
{% extends 'base.html' %}
{% block content_side_pannel %}
<p>This is a hair salon service application for 420 Final Project...</p>
{% endblock %}
{% block content_when_login %}
<li>Profile</li>

{% endblock content_when_login %}
{% block content_main_pannel %}
<h2>Welcome Home</h2>
<img id="home_image" src="{{url_for('static', filename='images/logo.jpg')}}" alt="Hair salon logo with scissors and comb.">
<div id="schedule-with-us">
<h4>Shedule An Appointment </h4>
    <p>(514) 928-2935</p>
    <p>Saloon.appointments@gmail.com</p>
    <a href=""><buton>Make Appointment</buton></a>
</div>
{% endblock %}

hairsalon_app/templates/macro.html
{% macro form_field_error(errors) %} 
    {% if errors %}
        <ul>
            {% for error in errors %}
                <li class='error-field'>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endmacro %}